use schooldb;
select * from SENSORS(
	ID			INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    PLACE		VARCHAR(20),
    TYPE		VARCHAR(20),
    VALUE		REAL,
    CREATED_AT		DATETIME DEFAULT CURRENT_TIMESTAMP
);

select * from SENSORS;
